Repository stan-dev/stanc3, pull requests merged in 2022-04, with the labels that each got.

#1112 Partially evaluate imaginary literals
  src/analysis_and_optimization/Partial_evaluator.ml
  test/integration/good/compiler-optimizations/cpp.expected
  test/integration/good/compiler-optimizations/cppO0.expected
  test/integration/good/compiler-optimizations/cppO1.expected
  test/integration/good/compiler-optimizations/partial-eval.stan
Labels: optimization

#1174 Expose cumulative sum for integers and complex types
  src/common/Helpers.ml
  src/middle/Stan_math_signatures.ml
  test/integration/good/function-signatures/math/matrix/cumulative_sum.stan
  test/integration/signatures/stan_math_signatures.t
Labels: feature

#1175 Pretty-print debug data using yojson
  src/analysis_and_optimization/Debug_data_generation.ml
  test/unit/Debug_data_generation_tests.ml
Labels: cleanup

#1097 Remove for loop trick for inlining functions w/o multiple returns + optims
  src/analysis_and_optimization/Mem_pattern.ml
  src/analysis_and_optimization/Mir_utils.ml
  src/analysis_and_optimization/Mir_utils.mli
  src/analysis_and_optimization/Monotone_framework.ml
  src/analysis_and_optimization/Optimize.ml
  test/integration/good/compiler-optimizations/cpp.expected
  test/integration/good/compiler-optimizations/cppO0.expected
  test/integration/good/compiler-optimizations/cppO1.expected
  test/integration/good/compiler-optimizations/dune
  test/integration/good/compiler-optimizations/function-in-function-inline.stan
  test/integration/good/compiler-optimizations/inline-functions-varmat.stan
  test/unit/Optimize.ml
Labels: cleanup, optimization

#1177 Show source code context with errors in Javascript
  src/frontend/Errors.ml
  src/frontend/Errors.mli
  src/middle/Location.ml
  src/stancjs/stancjs.ml
  test/stancjs/stancjs.expected
Labels: cleanup, stancjs

#1179 Clean up module interfaces
  src/common/Common.ml
  src/common/Common.mli
  src/frontend/Canonicalize.mli
  src/frontend/Frontend_utils.ml
  src/middle/Middle.ml
  src/middle/Stan_math_signatures.ml
  src/middle/Stan_math_signatures.mli
  src/stan_math_backend/Expression_gen.ml
  src/stan_math_backend/dune
  src/stanc/stanc.ml
  test/unit/Ast_to_Mir_tests.ml
  test/unit/Dataflow_utils.ml
  test/unit/Debug_data_generation_tests.ml
  test/unit/Dependence_analysis.ml
  test/unit/Desugar_test.ml
  test/unit/Factor_graph.ml
  test/unit/Optimize.ml
  test/unit/Parse_tests.ml
  test/unit/Semantic_check_tests.ml
  test/unit/Test_utils.ml
Labels: cleanup

#1180 Clean up MIR pretty printing code
  src/common/Fixed.ml
  src/common/Helpers.ml
  src/middle/Expr.ml
  src/middle/Index.ml
  src/middle/Program.ml
  src/middle/SizedType.ml
  src/middle/Stmt.ml
  src/middle/UnsizedType.ml
Labels: cleanup
